---

# Main tasks file for authentication role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::authentication'
    - 'role::authentication::init'


- name: 'KEYCLOAK | Deploy Docker compose project'
  include_role:
    name: "{{ _docker_service_role_full_name }}"
  tags:
    - 'role::authentication'
    - 'role::authentication::service'
  vars:
    _ansistrano_git_repo: "{{ authentication_git_repo }}"
    _ansistrano_git_branch: "{{ authentication_git_branch }}"
    _docker_service_compose_options: "{{ authentication_compose_options }}"
    _docker_service_compose_override: "{{ authentication_compose_override }}"
    _docker_service_compose_path: "{{ authentication_compose_path }}"
    _docker_service_files: "{{ authentication_files }}"
    _docker_service_project_name: "{{ authentication_project_name }}"
    _docker_service_templates: "{{ authentication_templates }}"
    _docker_service_networks: "{{ authentication_networks }}"
    _docker_service_volumes: "{{ authentication_volumes }}"
